In [6]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [7]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Dwarka,IN,2021-10-19 04:59:49,22.2394,68.9678,82.92,55,4,9.91
1,1,Morropon,PE,2021-10-19 04:59:49,-5.1822,-79.9689,71.67,75,100,2.48
2,2,Lubaczow,PL,2021-10-19 04:59:50,50.1570,23.1234,47.52,93,100,6.62
3,3,Ponta Do Sol,PT,2021-10-19 04:59:50,32.6667,-17.1000,76.01,26,96,0.87
4,4,Albany,US,2021-10-19 04:59:51,42.6001,-73.9662,44.80,85,31,11.01

In [8]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [9]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

InvalidWeightException: -3.93 is not a valid weight. Weights must be non-negative.

In [10]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
#list comprehension way of doing it
#heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])

In [11]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=100, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [16]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Dwarka,IN,2021-10-19 04:59:49,22.2394,68.9678,82.92,55,4,9.91
3,3,Ponta Do Sol,PT,2021-10-19 04:59:50,32.6667,-17.1000,76.01,26,96,0.87
7,7,Isangel,VU,2021-10-19 04:59:52,-19.5500,169.2667,80.71,78,75,0.00
8,8,Victoria,HK,2021-10-19 04:56:01,22.2855,114.1577,81.97,69,84,3.00
9,9,Tautira,PF,2021-10-19 04:59:53,-17.7333,-149.1500,80.62,79,80,18.23
17,17,Namatanai,PG,2021-10-19 04:59:56,-3.6667,152.4333,85.05,66,37,9.60
18,18,Marang,MY,2021-10-19 04:59:57,5.2056,103.2059,89.51,68,44,7.27
19,19,Sibolga,ID,2021-10-19 04:59:57,1.7427,98.7792,83.88,71,98,2.73
23,23,Rikitea,PF,2021-10-19 04:59:59,-23.1203,-134.9692,75.31,70,8,21.25
25,25,Cabo San Lucas,MX,2021-10-19 04:55:13,22.8909,-109.9124,81.61,79,100,8.97

In [17]:
preferred_cities_df.count()

City_ID       160
City          160
Country       160
Date          160
Lat           160
Lng           160
Max Temp      160
Humidity      160
Cloudiness    160
Wind Speed    160
dtype: int64

In [18]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
0           Dwarka      IN     82.92  22.2394   68.9678
3     Ponta Do Sol      PT     76.01  32.6667  -17.1000
7          Isangel      VU     80.71 -19.5500  169.2667
8         Victoria      HK     81.97  22.2855  114.1577
9          Tautira      PF     80.62 -17.7333 -149.1500
17       Namatanai      PG     85.05  -3.6667  152.4333
18          Marang      MY     89.51   5.2056  103.2059
19         Sibolga      ID     83.88   1.7427   98.7792
23         Rikitea      PF     75.31 -23.1203 -134.9692
25  Cabo San Lucas      MX     81.61  22.8909 -109.9124

In [39]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
hotel_df

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Dwarka,IN,82.92,22.2394,68.9678,Hotel Narayan Avezika Comfort
3,Ponta Do Sol,PT,76.01,32.6667,-17.1000,Hotel do Campo
7,Isangel,VU,80.71,-19.5500,169.2667,Tanna Lodge
8,Victoria,HK,81.97,22.2855,114.1577,Mini Hotel Central
9,Tautira,PF,80.62,-17.7333,-149.1500,Pension Oaoa
...,...,...,...,...,...,...
568,Sur,OM,88.86,22.5667,59.5289,Sur Plaza Hotel
572,Malakal,SS,78.40,9.5334,31.6605,Nile Palace Hotel
575,Gashua,NG,82.72,12.8710,11.0482,Forte Oil - Old Lorry Park
583,Fatick,SN,77.94,14.3581,-16.5858,
585,Wanning,CN,80.96,18.8003,110.3967,Paradise Hotel

In [19]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [22]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))